system         : "ISW sledge"
total_steps    : 990 # Total number of stepper motor steps 
total_length   : 0.42 # Length of the system [m] [between start and stop sensors]
speed_length   : 0.16 # Length of the distance between the sensors to meas the speed [m]
freq_init      : 300 # Frequency [Hz]
freq_set_min   : 5
freq_set_max   : 3000
invert_sensors : 0 # [0/1] 
motor_up_direction : clockwise # [clockwise/anticlockwise]
programs_filename : "programs.yaml"

ind_sensor_up: 3
ind_sensor_down: 0
ind_sensor_speed: [2,1]
